### ISSUE TITLE
Max Retries Error

### ISSUE THREAD

**Issue by linus727** [Sydiepus/mangadex-py#10]
I have this error quite often after 5ish Mangas done.
Maybe it's just my system, but I tried it under windows and linux overnight and booth threw the same error.
Could you build some error catcher around this, or some more retry logics?

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.mangadex.org', port=443):                                                                                                 Max retries exceeded with url: /chapter/f7d2717d-1f7f-482b-bcb8-246e7bd7ca3a (Caused by NewCo                                                                                                nnectionError('<urllib3.connection.HTTPSConnection object at 0x7f41d9665820>: Failed to estab                                                                                                lish a new connection: [Errno -3] Temporary failure in name resolution'))
`

**Comment by Sydiepus** [comment]
A `Temporary failure in name resolution ` is usually caused by a dns server could be your isp blocking it because of the huge amount of requests I'll to try to fix this with a better retry logic.

**Comment by linus727** [comment]
I had no issues so far after 90 Manga downloads overnight.

**Comment by Sydiepus** [comment]
ohhh that's an achievement.
