### ISSUE TITLE
Logic error when chapters are defined for each volume

### ISSUE THREAD

**Issue by linus727** [Sydiepus/mangadex-py#11]
Hey I found this error. Have a look at the following manga:
https://mangadex.org/title/0f4b813d-1d59-435a-9c0d-d759023e1c87
here all chapters are named 1-x for each individual volume and the downloader will only grab one "chapter 1" and not for each volume...

**Comment by Sydiepus** [comment]
fantastic i can finally make use of the volume variable.   
I'll work on it thanks for reporting.
