### ISSUE TITLE
Volumes Bug

### ISSUE THREAD

**Issue by linus727** [Sydiepus/mangadex-py#12]
Hey for some Mangas the Volumes are not detected right and rename it to some gibberish. See for the example manga:
https://mangadex.org/title/f6e7ce00-e09c-4ed2-b806-eb2fdc7a5f60/

```
getting uuid.
fetching manga info 'Title' 'description' 'status' based on your language setting.
No altTitles with that language found; using default title.
fetching chapters info 'available languages' 'available volumes if any' 'available chapters' 'total chapters (language independent)'.
-------------------------------------------
I, the Strongest Demon, Have Regained My Youth!
-------------------------------------------
fetching 'chapter list by language' 'total chapters by language.'
found 47 out of 225 for en
getting a server url to download the images from.
starting download
[('0', '1', '25ee61f4-4f61-417f-b779-a6971f6a6c51')]
skipping vol-1-chapter-0.zip
[('0', 'f8bb08f8-1d28-4358-950a-836c34af6dec')]
skipping vol-f8bb08f8-1d28-4358-950a-836c34af6dec-chapter-0.zip
[('1', '876f2b80-fd73-4fa2-9bd9-92bda08e64ec')]
skipping vol-876f2b80-fd73-4fa2-9bd9-92bda08e64ec-chapter-1.zip
[('1', 'ee4e7be2-abe5-4fd8-a92e-c9b97dab57b8')]
skipping vol-ee4e7be2-abe5-4fd8-a92e-c9b97dab57b8-chapter-1.zip
[('1', '789d1422-adb5-45cc-9c4d-eef9f4b61868')]
skipping vol-789d1422-adb5-45cc-9c4d-eef9f4b61868-chapter-1.zip
[('1', '66ee9c28-0126-4113-88c0-d0cb8f2d4c45')]
skipping vol-66ee9c28-0126-4113-88c0-d0cb8f2d4c45-chapter-1.zip
[('2', 'b71094fb-1be1-4765-9bc8-0770fbed5e50')]
skipping vol-b71094fb-1be1-4765-9bc8-0770fbed5e50-chapter-2.zip
[('2', 'f0f6dfd0-9955-4ff4-9e5d-1f9dd2758867')]
skipping vol-f0f6dfd0-9955-4ff4-9e5d-1f9dd2758867-chapter-2.zip
[('2', 'e7d85825-a1ff-4035-acaf-173c82d666e9')]
skipping vol-e7d85825-a1ff-4035-acaf-173c82d666e9-chapter-2.zip
[('2', '10dd2722-087b-49ed-a575-d1757a5c6334')]
skipping vol-10dd2722-087b-49ed-a575-d1757a5c6334-chapter-2.zip
[('3', '5d6e5c7e-ba02-47b8-8a87-a0b61aa93964')]
skipping vol-5d6e5c7e-ba02-47b8-8a87-a0b61aa93964-chapter-3.zip
[('3', '65756183-8194-4a58-8ceb-de00de1b5e33')]
Downloading vol-65756183-8194-4a58-8ceb-de00de1b5e33-chapter-3
using threads.
progress bar for threaded download broken.
zipping chapter folder.
[('3', '36f16b85-0908-4e73-921f-50b3d24ce370')]
Downloading vol-36f16b85-0908-4e73-921f-50b3d24ce370-chapter-3
using threads.
progress bar for threaded download broken.

```

**Comment by Sydiepus** [comment]
i think i know what's happening, the very first chapter of this manga have a vol and the rest doesn't which is causing this behavior i'll try to fix it.

**Comment by Sydiepus** [comment]
i now have a working fix not sure if it'll cause problems. 
what it does is that it makes sure that this chapter have a volume and name it vol-x-chapter-x
if not it'll use the chapter-x name.

**Comment by linus727** [comment]
yes that seems to be the case.
see here: this manga has volumes defined and some without
https://mangadex.org/title/255c1715-9a68-4e69-9647-ec833116e3d5/


```
zipping chapter folder.
[('41', '11', 'cefbcef5-b49c-4d38-a22a-67eecdd3dea8')]
Downloading vol-11-chapter-41
using threads.
progress bar for threaded download broken.
zipping chapter folder.
[('42', '11', '63f84032-c367-4ae4-a23b-5e2ba4bcc7b6')]
Downloading vol-11-chapter-42
using threads.
progress bar for threaded download broken.
zipping chapter folder.
[('43', '11', '51b1470c-c7f2-4d6c-bd76-bd56da7c4e1e')]
Downloading vol-11-chapter-43
using threads.
progress bar for threaded download broken.
zipping chapter folder.
[('44', '85585256-97e8-4f97-91f1-054da040c84a')]
Downloading vol-85585256-97e8-4f97-91f1-054da040c84a-chapter-44
using threads.
progress bar for threaded download broken.
zipping chapter folder.
[('45', 'd42eaaf1-7de9-4fdf-bbb1-6e72b55fea9c')]
Downloading vol-d42eaaf1-7de9-4fdf-bbb1-6e72b55fea9c-chapter-45
using threads.
progress bar for threaded download broken.
zipping chapter folder.
[('46', 'c4536219-6bb8-4f13-b865-d616c46077da')]
Downloading vol-c4536219-6bb8-4f13-b865-d616c46077da-chapter-46
using threads.
progress bar for threaded download broken.
```

**Comment by Sydiepus** [comment]
or maybe not that's the list of what will be downloaded for this manga.
```  [('1', '1', '7d6dce41-c15d-451f-9e73-dc3d106eebd9'), ('1', '7', '81969912-6e7f-446a-b44a-869112866f6c'), ('1', '8', '573d7cca-cc30-4810-8c5d-73cd93e5d3f1'), ('1', '9', 'd8c1adab-2398-4c19-bb44-a0d01fb4c03e'), ('1', '11', '6bda24f9-3a2c-40f8-a25c-6421d2132942'), ('1', '12', '1f82e598-32d9-4152-b6c4-1960f5a08dbd'), ('2', '1', '5bab03b4-3f67-4e8c-926d-c83ec74fe751'), ('2', '7', '738d00ac-a2a3-4e60-a7b4-be21f4c2a773'), ('2', '8', '421f3c76-50a6-44ed-9063-a57f93e3a6cd'), ('2', '9', '6d0cdf5b-d9b7-4741-87f6-43077554209a'), ('2', '11', '0ca40439-2314-4478-b54b-a41bde55640f'), ('3', '8', '04b6d0c0-ddf2-47c1-a24d-2b7dee0f6df4'), ('3', '9', 'b85dc656-8d10-4729-bb8f-0e193a95a882'), ('Oneshot', '66369c0d-4b2a-46f8-9c8c-a19d9f46a840')]```

**Comment by Sydiepus** [comment]
seems like it's being sorted by chapter which is why the oneshot will be the last to be downloaded.

**Comment by linus727** [comment]
Im testing it rn, lets see :D
The other samples i send before are behaving normal again.

**Comment by Sydiepus** [comment]
alright keep me updated i hope that it's going to work.

**Comment by linus727** [comment]
Ok, it's downloading it as "chapter-Oneshot" but this should contain if defined the volume number in the data structure, this way more than one oneshots from different volumes won't be overwritten and are easier to identify.

**Comment by Sydiepus** [comment]
this oneshot have no volume number.
i don't think it's possible to have more that one 'Oneshot' in the same manga/vol.
i think this is fine for now.

**Comment by linus727** [comment]
The Volume shown for the oneshot in volume 4 on the website can't be grabbed through the api?

![grafik](https://user-images.githubusercontent.com/61510392/131563493-38e67ae5-4011-4889-91dd-a0d2bf7c7243.png)

**Comment by Sydiepus** [comment]
it should be automatically grabbed which manga is this ?

**Comment by linus727** [comment]
this one:
https://mangadex.org/title/0f4b813d-1d59-435a-9c0d-d759023e1c87

**Comment by Sydiepus** [comment]
should be fixed.
