### ISSUE TITLE
I just found this bug where it downloads in bulk download the same chapters from the first manga and doesn't switch to the next one in the list after it finished it.

### ISSUE THREAD

**Issue by Sydiepus** [Sydiepus/mangadex-py#2]
I just found this bug where it downloads in bulk download the same chapters from the first manga and doesn't switch to the next one in the list after it finished it. So it will save the chapter from the first manga as the next one in line. See in the images that the file size is the exact same form different mangas. I also confirmed the pictures inside where the same and not from the actual manga that the folder is for.
![grafik](https://user-images.githubusercontent.com/61510392/131231020-9e8615db-b804-449c-993d-947e3144989f.png)

_Originally posted by @linus727 in https://github.com/Sydiepus/mangadex-py/issues/1#issuecomment-907689762_

**Comment by Sydiepus** [comment]
hello i can't reproduce the error on my end can you confirm if it's still there ?

**Comment by linus727** [comment]
As far as I can tell, it looks good. I will run the script on my NAS for today and see if I can spot any irregularities.

**Comment by Sydiepus** [comment]
Closing the issue since it's working with no issues.   
Feel free to reopen it if the error reoccurred.
