### ISSUE TITLE
2 translation group bug.

### ISSUE THREAD

**Issue by Sydiepus** [Sydiepus/mangadex-py#3]
there is some weird behavior when for one chapter two translation groups exist. It's trying to add additional images to the already existing zipfiles from the other translation group, in which case the picture order won't make any sense. Maybe a solution would be to add the translation group in brackets behind the chapter count.

_Originally posted by @linus727 in https://github.com/Sydiepus/mangadex-py/issues/1#issuecomment-907686877_

**Comment by Sydiepus** [comment]
i noticed that for different translation groups the images will have other x or a K this could be the problem i'll look into it.

**Comment by Sydiepus** [comment]
the problem is bigger than i thought it's the image naming that could one of the causes and some translation groups add a few extra pages which will be added later to the zip causing a messed chapter.   i'll try to fix it.

**Comment by linus727** [comment]
Wouldn't it be an option to download each chapter of booth groups and put the translation group name into the file structure. Either behind the image name inside the zip or outside as part of the zip name. Sometimes one translation group picks up a manga after another left it, so you would want all the chapter from booth groups...

**Comment by Sydiepus** [comment]
The goal of this project is download manga and be able to read them through a comic server or something.   
Downloading all avail chapters from different translators sometimes more than 2 would be a waste of storage and data since you don't need multiple version of the same chapter. I think it would be best to download the chapter with the most pages (or a random one) as a temporary solution maybe a permanent one.

**Comment by Sydiepus** [comment]
Moreover the program will download all chapters regardless of the translation group.

**Comment by linus727** [comment]
But can you handle the issue where another translation group picks up the manga that way? Also sometimes one group will translate a chapter in more than one batch, e.g one posts chapter 7 and another one 7.1 and 7.2 and 7.3...

**Comment by Sydiepus** [comment]
Yes, how I’m going to handle it is :    
1. Check if there’s multiple version of the chapter.   
2. Check which version contains the most pages.   
3. Remove all versions that weren’t selected.   
4. Download the chapter. 
5. Move to the one. 
6. Repeat.    
As you saw it doesn’t matter whether another group translated the next one or not it’ll download the chapter regardless of the group. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sydiepus** [comment]
do you know any manga with more than 2 scanlation for the same chapter ?

**Comment by Sydiepus** [comment]
> 
> 
> But can you handle the issue where another translation group picks up the manga that way? Also sometimes one group will translate a chapter in more than one batch, e.g one posts chapter 7 and another one 7.1 and 7.2 and 7.3...

now that i look at it this seems like another problem can you provide me with a manga with that kind of translation ?

**Comment by linus727** [comment]
> 
> 
> do you know any manga with more than 2 scanlation for the same chapter ?

I searched now for half an hour but couldn't find one...

> 
> 
> > But can you handle the issue where another translation group picks up the manga that way? Also sometimes one group will translate a chapter in more than one batch, e.g one posts chapter 7 and another one 7.1 and 7.2 and 7.3...
> 
> now that i look at it this seems like another problem can you provide me with a manga with that kind of translation ?

e.g here https://mangadex.org/title/0f237a5f-07ad-4e43-bbd9-2a320694434d?page=2
or here where chapter 22 is the to be expected chapter but 22.3 is a special
https://mangadex.org/title/10e98722-874d-48b2-a715-90bb8af93598
or here see chapter 28, where everyone following chapter 28.2 and 28.3 are one chapter together and no duplication of each other https://mangadex.org/title/173116b6-0f11-4fff-a348-8844d1394a45

**Comment by Sydiepus** [comment]
ohh okay i don't think that's a problem at all since they're not duplicates.

**Comment by Sydiepus** [comment]
i'll close this issue feel free to reopen it if the new update didn't fix the problem.   
In case a totally new bug was found please open a new issue.    
Thank you very much for reporting issue you encounter.
